PowerShell/Crescendo

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/ProxyViaSchema.Tests.ps1
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest1.txt
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest2.txt

Add tests to prove that the resultant module can be parsed by powershell 5

Fix framework to run on PowerShell 5

---

Microsoft.PowerShell.Crescendo/Samples/ifconfig.crescendo.json
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.Format.ps1xml
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.Types.ps1xml
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/ArgumentReturn.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ModuleAlias.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ProxyConfiguration.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ProxyContent.Tests.ps1
Microsoft.PowerShell.Crescendo/test/Streaming.Tests.ps1
Microsoft.PowerShell.Crescendo/test/assets/Alias.Proxy.json
Microsoft.PowerShell.Crescendo/test/assets/ArgProxy.noParam1.json
Microsoft.PowerShell.Crescendo/test/assets/ArgProxy.noParam2.json
Microsoft.PowerShell.Crescendo/test/assets/ArgProxy.withParam.json
Microsoft.PowerShell.Crescendo/test/assets/BulkProxy.json
Microsoft.PowerShell.Crescendo/test/assets/FullProxy.json
Microsoft.PowerShell.Crescendo/test/assets/HandlerFault1.json
Microsoft.PowerShell.Crescendo/test/assets/HandlerFault2.json
Microsoft.PowerShell.Crescendo/test/assets/HandlerFault3.json
Microsoft.PowerShell.Crescendo/test/assets/SimpleProxy.json
Microsoft.PowerShell.Crescendo/test/assets/StreamProxy.json
Microsoft.PowerShell.Crescendo/test/assets/dir.proxy.json
Microsoft.PowerShell.Crescendo/test/assets/ls.proxy.json
build.ps1

update tests to validate new behavior
add format and types file to improve experience
update tests to be unique function names in preparation for improved handling of duplicate functions

Emit aliases in the exported module

---

Microsoft.PowerShell.Crescendo/Samples/WinElevateWhoami.crescendo.json
Microsoft.PowerShell.Crescendo/Samples/dir.proxy.json
Microsoft.PowerShell.Crescendo/Samples/id.crescendo.json
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.Schema.json
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/Crescendo.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ExportCrescendoModule.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ModuleAlias.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ProxyViaSchema.Tests.ps1

Additional tests
Schema updates for supporting platform choice and Elevation
Crescendo now creates a PSD1 file now
Improved logic for parameter creation that handles parameters which are part of more than 1 parameter set.

Changes for elevation

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest1.txt
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest2.txt

Update test for new function content.

Update code for improved WhatIf behavior.

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.Schema.json
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/OutputHandler.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ProxyViaSchema.Tests.ps1
Microsoft.PowerShell.Crescendo/test/assets/MultiConfig.crescendo.json
Microsoft.PowerShell.Crescendo/test/assets/MultiHandler.json

Be sure to pass DefaultMissingValue if provided.
Minor fixes to schema.

Support Inline, Function, and Script output handlers.

---

README.md

@JamesWTruher, please review - update to readme
* Correction from issue #84 
* Added preview releases

Updated README with preview releases

---

README.md

Fix indentation in readme

---

Microsoft.PowerShell.Crescendo/Samples/id.crescendo.json
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/Crescendo.Issues.Tests.ps1
Microsoft.PowerShell.Crescendo/test/Crescendo.Tests.ps1
Microsoft.PowerShell.Crescendo/test/CrescendoClasses.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ExportCrescendoModule.Tests.ps1
Microsoft.PowerShell.Crescendo/test/MulitStageParameter.Tests.ps1
Microsoft.PowerShell.Crescendo/test/assets/ExampleInfo1.txt
Microsoft.PowerShell.Crescendo/test/assets/ExportCrescendoCommand1.json
Microsoft.PowerShell.Crescendo/test/assets/GetCrescendoConfiguration1.json
Microsoft.PowerShell.Crescendo/test/assets/ParameterInfo1.txt
Microsoft.PowerShell.Crescendo/test/assets/ParameterInfo2.txt
Microsoft.PowerShell.Crescendo/test/assets/ParameterInfo3.txt
Microsoft.PowerShell.Crescendo/test/assets/ParameterMap1.txt
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest1.txt
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest2.txt
Microsoft.PowerShell.Crescendo/test/assets/UsageInfo1.txt
build.ps1

Fixes 2 issues:
- #57 
- #100 
Add test option to build script to get code coverage
Fix a number of error messages to be more clear

Reduce test gaps and Issue fixes

---

Microsoft.PowerShell.Crescendo/schemas/2021-11
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1

create versioned schema.

---

Microsoft.PowerShell.Crescendo/schemas/2021-11

Update of 2021-11

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/ProxyContent.Tests.ps1
build.ps1

Do not distribute about help topic.
Help is part of docs repo: https://github.com/MicrosoftDocs/PowerShell-Docs-Modules/tree/main/reference/ps-modules/Microsoft.PowerShell.Crescendo.

Remove comment based help in module.

---

Microsoft.PowerShell.Crescendo/schemas/2022-06
Microsoft.PowerShell.Crescendo/test/Schema.Tests.ps1
build.ps1

Add tests.
Add the new schema to the package.

Add a description to schema entry for ApplyToExecutable.

---

build.ps1

run tests in a new pwsh process which does not load profile
Running tests in the current session may fail catastrophically if the environment is not controlled.

Isolate running tests to new process which does not load profile.

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1
Microsoft.PowerShell.Crescendo/test/Packaging.Tests.ps1

Add additional information to the module manifest.

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/ExportCrescendoModule.Tests.ps1

Add module version and schema information to generated module.
It is very difficult to know which version of crescendo created a module. This PR add the version of Crescendo which created the module and the schema that was used.

fix for Issue167

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1
Microsoft.PowerShell.Crescendo/test/Packaging.Tests.ps1
build.ps1

Update psd1 and enable the pending test for the new schema.

Changes for preview 1.

---

Microsoft.PowerShell.Crescendo/schemas/2022-06
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest1.txt
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest2.txt

This removes any output handling or output errors and just emits the output without any processing.

Add support for outputhandler 'Bypass'.

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1

Add icon to module manifest.

---

Microsoft.PowerShell.Crescendo/test/Packaging.Tests.ps1
Microsoft.PowerShell.Crescendo/test/PopCrescendoError.Tests.ps1
Microsoft.PowerShell.Crescendo/test/assets/ls.poperror.proxy.json

Add tests for pop-crescendoerror and push-crescendoerror

Add tests for push/pop CrescendoError

---

.ci/ci.yml
Microsoft.PowerShell.Crescendo/Samples/ifconfig.crescendo.json
Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest1.txt
Microsoft.PowerShell.Crescendo/test/assets/ProxyContentTest2.txt

Fix tests for argument transform.
Add TODO for fixing serialization to multiple files.

Fix formatting of a couple of functions.

---

README.md

@JamesWTruher, @sdwheeler - Please review for 1.1.0 additions to readme.

Updated Readme to reflect 1.1.0 additions

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psm1
Microsoft.PowerShell.Crescendo/test/ExportCrescendoCommand.Tests.ps1
Microsoft.PowerShell.Crescendo/test/ExportCrescendoModule.Tests.ps1
Microsoft.PowerShell.Crescendo/test/Packaging.Tests.ps1
Microsoft.PowerShell.Crescendo/test/assets/ExportCrescendoCommand1.json

It wasn't using the new format for multiple commands.
Add validation for the exported configurations will work with Export-CrescendoModule.
Fix up other tests affected by this change.

Fixup serialization when calling ExportConfigurationFile.

---

.ci/releaseBuild.yml
Microsoft.PowerShell.Crescendo/test/CrescendoClasses.Tests.ps1

use proper demand when running TSA upload.

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1

update version to RC1.

---

Microsoft.PowerShell.Crescendo/src/Microsoft.PowerShell.Crescendo.psd1

remove the prerelease tag for 1.1 GA

Remove Prerelease tag for 1.1 GA.

---

.config/suppress.json
.config/tsaoptions.json
.pipelines/Crescendo-Official.yml
build.ps1
global.json
nuget.config

Move to OneBranch for sign/release

---

.pipelines/Crescendo-Official.yml

parameterize the OneBranch build publishing stage

---

.pipelines/Crescendo-Official.yml

be sure that master matches OneBranch
